### ISSUE TITLE
Documentation should clarify the version of Docker Compose needed when installed from source

### ISSUE THREAD

**Issue by Gregg-Hendrix** [lando/docs#174]
Just rubber ducking this here:

I knew that I shouldn't have installed the new version of lando...I just got SO excited by everyone updating! Does anyone have any insight on this error?

After running `lando start` I got this : 

```
ERROR ==> Error: (HTTP code 404) no such container - No such container: landoproxyhyperion5000gandalfedition_proxy_1  message=Error: (HTTP code 404) no such container - No such container: landoproxyhyperion5000gandalfedition_proxy_1 , stack=Error: Error: (HTTP code 404) no such container - No such container: landoproxyhyperion5000gandalfedition_proxy_1 
    at /snapshot/cli/lib/docker.js
    at processImmediate (internal/timers.js:464:21)
From previous event:
    at containerOpt (/snapshot/cli/lib/docker.js)
    at Landerode.scan (/snapshot/cli/lib/docker.js)
    at Object.scan (/snapshot/cli/lib/router.js)
    at run (/snapshot/cli/lib/engine.js)
    at /snapshot/cli/lib/router.js
From previous event:
    at Object.eventWrapper (/snapshot/cli/lib/router.js)
    at Engine.engineCmd (/snapshot/cli/lib/engine.js)
    at Engine.scan (/snapshot/cli/lib/engine.js)
    at /snapshot/cli/plugins/lando-networking/app.js
From previous event:
    at AsyncEvents.<anonymous> (/snapshot/cli/plugins/lando-networking/app.js)
    at AsyncEvents.handle (/snapshot/cli/lib/events.js)
    at /snapshot/cli/lib/events.js
    at processImmediate (internal/timers.js:464:21)
From previous event:
    at AsyncEvents.emit (/snapshot/cli/lib/events.js)
    at /snapshot/cli/lib/app.js
From previous event:
    at App.start (/snapshot/cli/lib/app.js)
    at Object.run (/snapshot/cli/plugins/lando-core/tasks/start.js)
    at /snapshot/cli/lib/cli.js
    at processImmediate (internal/timers.js:464:21)
From previous event:
    at /snapshot/cli/lib/cli.js
From previous event:
    at Object.handler (/snapshot/cli/lib/cli.js)
    at Object.runCommand (/snapshot/cli/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/snapshot/cli/node_modules/yargs/yargs.js:1063:30)
    at Function.get [as argv] (/snapshot/cli/node_modules/yargs/yargs.js:1004:21)
    at Cli.init (/snapshot/cli/lib/cli.js)
    at Cli.run (/snapshot/cli/lib/cli.js)
    at Object.<anonymous> (/snapshot/cli/bin/lando.js)
    at Module._compile (pkg/prelude/bootstrap.js:1751:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.runMain (pkg/prelude/bootstrap.js:1804:12)
    at internal/main/run_main_module.js:17:47, __stackCleaned__=true

```
I then ran lando rebuild  and got this error :

```
ERROR ==> database reported as unhealthy. 
ERROR ==> Error: (HTTP code 404) no such container - No such container: landoproxyhyperion5000gandalfedition_proxy_1 
```

I'm SUPER out of my depth with lando in general (haha). I'm thinking that since I don't really know what I'm doing...Perhaps the best thing for me is to uninstall and re-install the previous version that was working? Any thoughts would be appreciated

P.s - I tried a `lando poweroff `

and

`lando destroy`

**Comment by sirdiego** [comment]
> If you install one of Lando's package installers it should install the correct version of Docker Compose so i'm guessing this is only relevant if you are installing Lando from source. We should update those docs so its clear what version of Docker Compose is required: https://docs.lando.dev/basics/installation.html#from-source

That makes sense. We just installed it via package manager, which is also referenced inside the docs. So maybe a hint there would be good as well. I think the installation via package manager will be broken until Docker Compose 2 support is there.

Downgrading the docker-compose package to 1.29.x manually fixes the problems. For everyone needing an old Docker Composer version for ArchLinux, you can download it here: https://archive.archlinux.org/packages/d/docker-compose/

**Comment by hparadiz** [comment]
Just want to say that if someone actually updated the docs it would have saved me hours of hassle. Just update the docs!

**Comment by anibalsanchez** [comment]
Same issue here.

Weirdly, this command fixed the issue:

``` 
docker rename 230653d52982_landoproxyhyperion5000gandalfedition_proxy_1 landoproxyhyperion5000gandalfedition_proxy_1
```

The docker and docker-compose versions don't change the results.

```docker version
Client: Docker Engine - Community
 Version:           20.10.14
 API version:       1.41
 Go version:        go1.16.15
 Git commit:        a224086
 Built:             Thu Mar 24 01:47:58 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.14
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.15
  Git commit:       87a90dc
  Built:            Thu Mar 24 01:45:50 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.5.11
  GitCommit:        3df54a852345ae127d1fa3092b95168e4a88e2f8
 runc:
  Version:          1.0.3
  GitCommit:        v1.0.3-0-gf46b6ba
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
``` 

```
docker-compose version
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Comment by radmen** [comment]
FYI: Lando doesn't work with `docker-compose` 2.12.2. I had to downgrade it to 1.29.2 to have it work.

The issue is similar to this thread. The `traefik` instance is renamed to `landoproxyhyperion5000gandalfedition-proxy-1`. using the `docker rename` solution didn't work in my case.

**Comment by elvismdev** [comment]
Upgrading to the Lando pre-release v3.8.0 fixed the problem for me: https://github.com/lando/lando/releases/tag/v3.8.0
